#ifndef ADC_INIT_EGURM_H
#define ADC_INIT_EGURM_H

#include "adc_egurm.h"

#define ADC_EGURM_RCU_GPIO							RCU_GPIOC
#define ADC_EGURM_DM__RCU_GPIO					RCU_GPIOA
#define ADC_EGURM_RCU_ADC								RCU_ADC0
#define ADC_EGURM_RCU_DMA								RCU_DMA0

#define ADC_EGURM_GPIO									GPIOC
#define ADC_EGURM_DM__GPIO							GPIOA

#define ADC_EGURM_VCC_GPIO_PIN					GPIO_PIN_0		// GPIOC
#define ADC_EGURM_CURR_GPIO_PIN					GPIO_PIN_1		// GPIOC
#define ADC_EGURM_MOM_IN_GPIO_PIN				GPIO_PIN_2		// GPIOC
#define ADC_EGURM_MOM_OUT_GPIO_PIN			GPIO_PIN_3		// GPIOC
#define ADC_EGURM_TEMPER_GPIO_PIN				GPIO_PIN_4		// GPIOC
#define ADC_EGURM_CUR_ING_GPIO_PIN			GPIO_PIN_5		// GPIOC
#define ADC_EGURM_CUR_mA_GPIO_PIN				GPIO_PIN_0		// GPIOB
#define ADC_EGURM_DM_1_GPIO_PIN					GPIO_PIN_0		// GPIOA
#define ADC_EGURM_DM_2_GPIO_PIN					GPIO_PIN_4		// GPIOA
#define ADC_EGURM_DM_3_GPIO_PIN					GPIO_PIN_5		// GPIOA
#define ADC_EGURM_DM_4_GPIO_PIN					GPIO_PIN_6		// GPIOA

#define ADC_EGURM_DMA										DMA0
#define ADC_EGURM_DMA_CH								DMA_CH0
#define ADC_EGURM_ADC										ADC0

#define ADC_EGURM_DM_1_ADC_CHANNEL			ADC_CHANNEL_0
#define ADC_EGURM_DM_2_ADC_CHANNEL			ADC_CHANNEL_4
#define ADC_EGURM_DM_3_ADC_CHANNEL			ADC_CHANNEL_5
#define ADC_EGURM_DM_4_ADC_CHANNEL			ADC_CHANNEL_6
#define ADC_EGURM_VCC_ADC_CHANNEL				ADC_CHANNEL_10
#define ADC_EGURM_CURR_ADC_CHANNEL			ADC_CHANNEL_11
#define ADC_EGURM_MOM_IN_ADC_CHANNEL		ADC_CHANNEL_12
#define ADC_EGURM_MOM_OUT_ADC_CHANNEL		ADC_CHANNEL_13
#define ADC_EGURM_TEMPER_ADC_CHANNEL		ADC_CHANNEL_14
#define ADC_EGURM_CUR_INJ_ADC_CHANNEL		ADC_CHANNEL_15

void AdcEgurnInit(void);
void AdcRcuConfig(void);
void AdcGpioConfig(void);
void AdcDmaConfig(void);
void AdcConfig(void);

#endif
