#pragma once
#include "sense_valeo.h"


//#define VALEO_EGURM_DM1_GPIO								GPIOA
//#define VALEO_EGURM_DM2_GPIO								GPIOA
//#define VALEO_EGURM_DM3_GPIO								GPIOA
//#define VALEO_EGURM_DM4_GPIO								GPIOA
//
//#define VALEO_EGURM_DM_1_GPIO_PIN						GPIO_PIN_0		// GPIOA
//#define VALEO_EGURM_DM_2_GPIO_PIN						GPIO_PIN_4		// GPIOA
//#define VALEO_EGURM_DM_3_GPIO_PIN						GPIO_PIN_5		// GPIOA
//#define VALEO_EGURM_DM_4_GPIO_PIN						GPIO_PIN_6		// GPIOA

#define VALEO_IN_PWM_DM1_RCU_TIMER					RCU_TIMER1
#define VALEO_IN_PWM_DM2_RCU_TIMER					RCU_TIMER9
#define VALEO_IN_PWM_DM3_RCU_TIMER					RCU_TIMER10
#define VALEO_IN_PWM_DM4_RCU_TIMER					RCU_TIMER12

#define VALEO_IN_PWM_DM1_RCU_GPIO						RCU_GPIOA
#define VALEO_IN_PWM_DM2_RCU_GPIO						RCU_GPIOB
#define VALEO_IN_PWM_DM3_RCU_GPIO						RCU_GPIOB
#define VALEO_IN_PWM_DM4_RCU_GPIO						RCU_GPIOA

#define VALEO_IN_PWM_DM1_GPIO								GPIOA
#define VALEO_IN_PWM_DM2_GPIO								GPIOB
#define VALEO_IN_PWM_DM3_GPIO								GPIOB
#define VALEO_IN_PWM_DM4_GPIO								GPIOA

#define VALEO_IN_PWM_DM1_GPIO_PIN						GPIO_PIN_0
#define VALEO_IN_PWM_DM2_GPIO_PIN						GPIO_PIN_8
#define VALEO_IN_PWM_DM3_GPIO_PIN						GPIO_PIN_9
#define VALEO_IN_PWM_DM4_GPIO_PIN						GPIO_PIN_6

#define VALEO_IN_PWM_DM1_TIMER							TIMER1
#define VALEO_IN_PWM_DM2_TIMER							TIMER9
#define VALEO_IN_PWM_DM3_TIMER							TIMER10
#define VALEO_IN_PWM_DM4_TIMER							TIMER12

#define VALEO_IN_PWM_DM1_PERIOD							10000
#define VALEO_IN_PWM_DM2_PERIOD							10000
#define VALEO_IN_PWM_DM3_PERIOD							10000
#define VALEO_IN_PWM_DM4_PERIOD							10000

#define VALEO_IN_PWM_DM1_PRESCAL						168
#define VALEO_IN_PWM_DM2_PRESCAL						168
#define VALEO_IN_PWM_DM3_PRESCAL						168
#define VALEO_IN_PWM_DM4_PRESCAL						168

#define VALEO_IN_PWM_DM1_TIMER_IRQn					TIMER1_IRQn
#define VALEO_IN_PWM_DM2_TIMER_IRQn					TIMER0_UP_TIMER9_IRQn
#define VALEO_IN_PWM_DM3_TIMER_IRQn					TIMER0_TRG_CMT_TIMER10_IRQn
#define VALEO_IN_PWM_DM4_TIMER_IRQn					TIMER7_UP_TIMER12_IRQn

#define	VALEO_IN_PWM_DM1_TIMER_IRQHandler		TIMER1_IRQHandler
#define	VALEO_IN_PWM_DM2_TIMER_IRQHandler		TIMER0_UP_TIMER9_IRQHandler
#define	VALEO_IN_PWM_DM3_TIMER_IRQHandler		TIMER0_TRG_CMT_TIMER10_IRQHandler
#define	VALEO_IN_PWM_DM4_TIMER_IRQHandler		TIMER7_UP_TIMER12_IRQHandler

void ValeoTimersInit(void);
